name: Dispatch test

on:
  repository_dispatch:
    types: test

  workflow_dispatch:
    inputs:
      paramName:
        description: 'Param'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:

      - name: Retrieve param from input
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "PARAM=${{github.event.input.paramName}}" >> $GITHUB_ENV
      - name: Retrieve param from payload
          if: ${{ github.event_name == 'repository_dispatch' }}
          run: |
            echo "PARAM=${{github.event.input.paramName}}" >> $GITHUB_ENV
      - name: Run provider contract verification
        env:
          PARAM: ${{env.PARAM}}
        run: |
          echo $PARAM
