name: Dispatch test

on:
  repository_dispatch:
    types: test

  workflow_dispatch:
    inputs:
      paramName:
        description: 'Param'
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:

      - name: Run provider contract verification
        env:
          PARAM: ${{github.event.client_payload.paramName || github.event.inputs.paramName}}
        run: |
          echo $PARAM
